name: test
on:
  push:
    branches:
      - dev
      - stage
      - prod
      - hotfix
  pull_request:
    branches:
      - feature/*
    types: [ opened, synchronize ]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: pytest
        run: poetry run pytest
